### ISSUE TITLE
Interface for retrieving objects via `all_objects` function

### ISSUE THREAD

**Issue by RNKuhns** [sktime/BaseObject#23]
**Is your feature request related to a problem? Please describe.**
Providing generic functionality for retrieving `BaseObjects`. This functionality should be flexible enough to easily work in other projects.

**Describe the solution you'd like**
`BaseObject` will include an `all_objects` function (similar to `all_estimators` in `sktime` and `scikit-learn`). However, in both of those projects the root path of the search for objects is known (so it can be hard coded in the function). Since the `BaseObject` package is designed for use by other packages, this needs to be determined when the function is used in a given project.

Currently `all_objects` is determining the root path using:

```python
def all_objects(...):
    ...
    root = str(Path(__file__).parent.parent)
    ...
```
However, this prescribes an expected hierarchy on where the `all_objects` function will reside in a project relative to the root. This fits with the design of `sktime`; however, within `BaseObject` there is not the same nesting of submodules, so the current approach would likely lead the root to be specified one-level higher than it should be. On other projects, the degree of module "nesting" could be more or less (in a more nested project the approach above would find a root below the project's actual root).

To solve this we should make it so that the user can specify the information needed to identify the root where the object retrieval search should start.

I've identified 2 options (there could be others) that would allow this information to be provided:

1. Add a parameter to `all_objects` (it could be called path or root or something like that) that lets users specify the location they want `all_objects` to start their search in (it would then recursively search from that location).
2. Derive the root path from the `package_name` parameter that is already part of the `all_objects` API interface by importing the specified package name and using the `__path__` and `__file__` information

The nice thing about solution 2 is that we don't need the user to specify additional information. That solution would involve deteriming the path based on `package_name` with some code like this:

```python
def all_objects(...):
    ...
    module = importlib.import_module(package_name)
    if hasattr(module, "__path__"):
        path = module.__path__[0]
    elif hasattr(module, "__file__") and module.__file__ is not None:
        path = module.__file__.split(".")[0] # remove .py or other related file ending
    else:
        ... # we'd raise some error
    ...
    
```

However, it is unclear if there are edge cases we would want to support that it would not be able to handle. For example, the [Python docs](https://docs.python.org/3/reference/import.html#package-path-rules) note that `__file__` is optional. On the other hand, it seems like `__path__` is always set, but it is an iterable and there are some edge cases where there could be multiple paths (e.g. [this](https://stackoverflow.com/questions/2699287/what-is-path-useful-for)).

**Comment by fkiraly** [comment]
I see, thanks for explaining!

How about option 3, which combines the two?
* two arguments, `module` and `package` or similar
* the location is `module` (relative path to `package`) in `package`
* if `module` is `None`, it is package root
* if `package` is `None`, it is the package the function lives in

This would allow to treat the two cases both:
* submodule of current package
* another package

**Comment by fkiraly** [comment]
(either way, I think we should only minimally depart from what is currently in `sktime` to avoid adding too many new features or changes in functionality before we have refactored the location)

**Comment by RNKuhns** [comment]
Agree we don't want to depart from sktime much as we refactor the location. My plan would be for us to use the solution we pick in both the `package_metadata` function I added and also `all_objects`. We'll save the integration of those pieces until later.

But I need a clarification on the proposed `module` and `package` parameters. 

I'm not sure we need the path relative to the package specified in `package` parameter. As the function exists in #11 currently, there is a param called `package_name` that is used as the prefix (with "." concatenated at the end) in the search that walks sub module/packages. I'm assuming `package` and that would be the same. If someone passed "sktime.forecasting" to that parameter and sktime was importable, we would be able to look up the path for `sktime.forecasting` and the walk it (also using "sktime.forecasting" as the prefix).

If users can specify the modules and or sub-modules that way (they could specify "sktime.forecasting.probabalistic" too, and so on for any hierarchy), is there a need for `module` to capture the path relative to the package? 

If not, can't we just use `package` to let the user specify the sub-module path they want to start inspecting?

**Comment by fkiraly** [comment]
Have you thought through whether any problems will occur if `all_objects` is called in a third party package? I.e., do the relative root folder changes cause problems, if `all_objects` lives in a package we import rather than the package we build?

If that is all fine, I don't mind using only one argument.
