### ISSUE TITLE
Giving proper credit

### ISSUE THREAD

**Issue by fkiraly** [sktime/BaseObject#3]
I think multiple individuals have contributed to `BaseObject`, the two major code sources are `sklearn` and myself. Idea sources also include @mloning and @rnkuhns. We should make sure that we also don't forget anyone else, especially since copy-pasting of code is happening here and commit history is hence obscured. References to the  main original locations are required for giving proper credit.

**Comment by RNKuhns** [comment]
@fkiraly, I agree. We should reference sklearn in either a comment block or module docstring in the applicable code files (do you know the convention there?). In terms of the sktime folks (you, Marcus and I), we can explicitly list people in an all-contributors file. I'm adding that in a PR.
