### ISSUE TITLE
Refactor sktime tests and inspection&search to live in baseobject package

### ISSUE THREAD

**Issue by fkiraly** [sktime/BaseObject#4]

**Comment by RNKuhns** [comment]
@fkiraly we'll need to update ``get_test_params(cls, parameter_set="default")`` for this to work. It assumes tests are imported from location in sktime.

Some initial solutions, I've considered (no particular order):

1. Use the "config" interface I've added in my repo (note that scikit-learn is using a config interface to change behavior of ``BaseEstimator``, e.g. how it pretty prints, etc). Idea would be that a package that uses ``BaseObject`` uses ``set_config`` prior to importing ``BaseObject``
2. Provide a decorator that can be used to set this in inherited objects.
3. Require inheriting classes to have an attribute or use a tag that allows this functionality to work
4. Add param to function, requiring users to pass the test location (this is not ideal solution b/c  having to provide that constantly is not good for users, and we'd have to add the param to other methods that call this internally, which exacerbates that problem)

**Comment by fkiraly** [comment]
just for the record, from what was discussed verbally:

`get_test_params` default in `sktime` `BaseObject` ist just importing from elsewhere to be downwards compatible with legacy situation where test params would all sit in one file rather than with their estimator/object.

This will be removed eventually, in favour of a default "return empty dict". New estimators do not import any fixed location but return a list of dicts of test parameters.

That is what we decided to do, in the end.

**Comment by RNKuhns** [comment]
@fkiraly just wanted to confirm what is meant about new estimators not importing from any fixed location. 

I agree with the current initial refactor part and defaulting to empty dicts down the road. But wanted to clarify what the other part meant.

Is the no fixed location part implying that we will give people the option to configure a dynamic location (and otherwise default to empty dict if they don't do it)?

As an example, that would mean you could set BaseObject to look in the correct directory for test params in sktime when used in sktime, and others could configure their location in their packages (and if not it defaults to empty dict).

That would be very nice for.

**Comment by fkiraly** [comment]
>Is the no fixed location part implying that we will give people the option to configure a dynamic location (and otherwise default to empty dict if they don't do it)?

No, I did not mean "configurable but fixed location", but "no reference to any extrinsic location at all", in my post above.

What we do in the end (as opposed to what I meant above) is of course up for discussion, currently I would favour having test parameters with the estimator, instead of collecting them all in one place. That has caused so many problems with `sktime`, amongst others a substantial complication of the extender contract (it seels like a little, but it is substantial due to the overhead of communication and understanding complexity required here).

**Comment by fkiraly** [comment]
> The only difficulty is including test params in composite estimators (and where to import things). We can cross that bridge once we get there.

In `sktime`, we adopted the convention that component imports must happen inside `get_test_params`, or it is really easy to end up with circular imports.

**Comment by fkiraly** [comment]
FYI, I have been separating object from estimator tests in `sktime`, that has been a bit of a hassle: https://github.com/alan-turing-institute/sktime/pull/3122

This constitutes the major step on the `sktime` side, since we now have a well-defined scope that can be replaced by a `baseobject` import.

**Comment by fkiraly** [comment]
I think this is done:

* `sktime` no longer relies on `_config` to retrieve estimator test parameters
